# Generated by Django 5.1.7 on 2025-03-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(blank=True, default='', max_length=100)),
                ('specific_name', models.CharField(blank=True, default='', max_length=100)),
                ('common_name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.FloatField()),
                ('date_obtained', models.DateField()),
                ('date_died', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('next_owner', models.CharField(blank=True, default='', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.plant')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.species')),
            ],
            options={
                'ordering': ['date_obtained'],
            },
        ),
    ]
