# Generated by Django 5.1.7 on 2025-03-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='next_owner',
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('new_owner', models.CharField(blank=True, default='', max_length=100)),
                ('plant_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.plant')),
            ],
        ),
    ]
