# Generated by Django 5.1.7 on 2025-04-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(blank=True, default='', max_length=100)),
                ('specific_name', models.CharField(blank=True, default='', max_length=100)),
                ('common_name', models.CharField(blank=True, default='', max_length=100)),
                ('light_requirements', models.CharField(blank=True, default='', max_length=100)),
                ('watering_frequency', models.CharField(blank=True, default='', max_length=100)),
                ('soil_type', models.CharField(blank=True, default='', max_length=100)),
                ('temperature_range', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.FloatField()),
                ('date_obtained', models.DateField()),
                ('date_died', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='plantTracker.plant')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantTracker.species')),
            ],
            options={
                'ordering': ['date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('new_owner', models.CharField(blank=True, default='', max_length=100)),
                ('plant_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transfer', to='plantTracker.plant')),
            ],
        ),
    ]
